### ISSUE TITLE
backend route for get one repo details

### ISSUE THREAD

**Issue by ssarda77** [sballan/grille#53]

**Comment by sballan** [comment]
Here's an issue to consider - if there is more than one repo in our database with the same name, the route as currently written will fail.  We need to find out the owner of the repo in question  before we do this search, so that we can be sure which is the correct repo.

I'm pretty sure when you do the "get all", it will tell you who the owner of each repo is.  There are also methods that will let you get all the collaborators for a repo if that's helpful.
